### ISSUE TITLE
Got an error cannot import name from Pyfhel 

### ISSUE THREAD

**Issue by 123alikaha** [ibarrond/Pyfhel#102]
### **I got this error run the each Demo**

> Traceback (most recent call last):
>   File "D:/Clustering/Pyfhel-master/Pyfhel-master/examples/Demo_HelloWorld.py", line 17, in <module>
>     from Pyfhel import Pyfhel, PyPtxt, PyCtxt
>   File "D:\Clustering\Pyfhel-master\Pyfhel-master\Pyfhel\__init__.py", line 1, in <module>
>     from Pyfhel import Pyfhel
> ImportError: cannot import name 'Pyfhel' from partially initialized module 'Pyfhel' (most likely due to a circular import) (D:\Clustering\Pyfhel-master\Pyfhel-master\Pyfhel\__init__.py)

**Comment by 123alikaha** [comment]
@ibarrond sorry for late reply due to some reasons Debug Error: (<class 'ImportError'>, ImportError("cannot import name 'PyPtxt' from 'Pyfhel' (/home/ali/Downloads/Pyfhel-master/Pyfhel/__init__.py)"), <traceback object at 0x7f9279923740>) and screenshot -----> https://ibb.co/cCY3Vn4

**Comment by ibarrond** [comment]
@123alikaha Again, please use the "bug" template to create an issue describing everything at once. I'm missing information to investigate the issue!

**Comment by ibarrond** [comment]
When you create a new issue in the Pyfhel Github repo, you can choose between "Bug Report" and "Features". Please open a new issue, choose "Bug Report" and fill the entire form/template with all the requested details. I pasted the Bug form/template 8 days ago in a comment above, but instead of following it you answered with yet a different error.

**Comment by 123alikaha** [comment]
@ibarrond sure i will thanks
