### ISSUE TITLE
What is the range of m?

### ISSUE THREAD

**Issue by EchizenG** [ibarrond/Pyfhel#116]
**Describe the feature**
I was trying to encrypt a large vector(size>40000) in batch mode. So I need to enlarge the m in contextGen() to over 40000.(I think so). When I do this, there is an error report:

File "testBatchPyfhel.py", line 20, in <module>
    HE.contextGen(p=p,m=m, base=2, sec=192, flagBatching=True)
  File "Pyfhel/Pyfhel.pyx", line 182, in Pyfhel.Pyfhel.Pyfhel.contextGen
  File "Pyfhel/Pyfhel.pyx", line 216, in Pyfhel.Pyfhel.Pyfhel.contextGen
IndexError: no default parameters found

I also met this error when I wanted to set m to 25 or some small number like this.
Is there any range for m? Thank you!

**Is this feature related to a project/objective? Please describe briefly**
I want to know how to use Pyfhel correctly.

**Comment by AlexanderViand** [comment]
Hi Echizen! The error message is pretty much spot-on: Pyfhel couldn't find a valid set of default parameters for the underlying cryptosystem that match `m=400000`. 

In order to take advantage of the default parameters, you will want to set `m` to a power of two (e.g. 32768) and it will also need to be above a certain minimum size (>1024, maybe >2048? I can't recall right now). The latter is required since ensuring the security of the underlying scheme implies minimum sizes of `m`, while the power-of-two one is a de-facto limitation of the implementation.

You should also be aware that 32k or 64k are very large parameter instances, so performance might suffer a bit, especially around key generation.

**Comment by EchizenG** [comment]
That makes sense! However, I tried set m=65536 while p=1964769281. It still reported that error. Any other potential issues? Thank you!

**Comment by AlexanderViand** [comment]
64k is a very large parameter size and there aren't yet any standardized parameter sets at this size. While it should technically be possible to use such large parameters in Pyfhel by manually providing all parameters, this requires a pretty good understanding of the reserach literature on the topic to ensure security & efficiency.

It'll probably be more efficient to split a large input array into multiple smaller (16k or 32k) ciphertexts rather than trying to come up with custom parameters for 64k.

**Comment by EchizenG** [comment]
Got your idea! Thank you so much!
