### ISSUE TITLE
array sum

### ISSUE THREAD

**Issue by meirgold** [ibarrond/Pyfhel#143]
For a project I'm working on, I need to sum up the numbers in an encrypted array, expecting the sum to appear in the first cell and have all othes contain zeros.
I tried doing this by splitting the array into 2, summing both halves, repeating until I'm left with a single cell.
In order to achieve this, I used shift operations.
I noticed that if I later shift the summed array to the right, the numbers which were shifted left out of the array bounds return.
I would have expected to get zeros as the original numbers were shifted out of the boundries. Is this expected behaviour?
Is there a better recommend way for summing an array?

**Comment by AlexanderViand** [comment]
The "shifts" are actually cyclical rotations so yes, this is expected behavior. 

What you should do is first use the "copy-rotate-sum" technique that you've already stumbled upon to create a ciphertext where each slot (your 'cell') contains the full sum. Then you can multiply that with a plaintext vector that is 0 in all positions except the first slot. 

I think you already know how to do this, but just in case: here's a visualization of the "copy-rotate-sum" technique for four elements. It scales up to larger sizes logarithmically:
![image](https://user-images.githubusercontent.com/4427806/193010484-d84db707-8b7b-4ae6-9fe1-33125706b24a.png)

**Comment by meirgold** [comment]
Thanks very much  Alexander for the detailed explanation and example.
In my program I'm using a BFV context with n=2**13, so it seems that I have 8192 cells in the encrypted array.
If I fill my array with 3 non-zero numbers in indices 0,1 and 2, shift 2 of them out of bounds, decrypt and then print indices 8190 and 8191 I see their values are 0.  This led me to the conclusion that the shift isn't cyclic.
How come I cannot see the numbers in the high indices after decryption?

**Comment by AlexanderViand** [comment]
Any chance that the shift/rotation is going the other way than you expect?
` [ a | b | c | 0 | ... | 0 ]` should get (iirc) rotated to `[ 0 | 0 | a | b | c | 0 | ... | 0 ]` if rotated by +2. 
What you probably want is rotation by -2, so you get ` [ c | 0 | ... | 0 | b | a ]`, right?

**Comment by meirgold** [comment]
The shift is going the way I expected. The expected result is as you indicated: `[ c | 0 | ... | 0 | b | a ]`
Instead I get `[ c | 0 | ... | 0 | 0 | 0 ]`

The code I am using is as following:
`
HE = Pyfhel()
HE.contextGen("bfv", n=2 ** 13, t=65537, sec=128)
HE.keyGen()  
HE.rotateKeyGen() 
HE.relinKeyGen()  
arr3 = np.array([1, 2, 3])
ptxt3 = HE.encodeInt(arr3)
ctxt3 = HE.encryptPtxt(ptxt3)
ccshift = ctxt3 << 2
ccshift_dec = HE.decryptInt(ccshift)
print("last: ", ccshift_dec[8190])
print("first: ", ccshift_dec[0])
`
The output is:  
last:  0
first:  3

**Comment by meirgold** [comment]
The shift is going the way I expected. The expected result is as you indicated: `[ c | 0 | ... | 0 | b | a ]`
Instead I get `[ c | 0 | ... | 0 | 0 | 0 ]`

The code I am using is as following:
HE = Pyfhel() HE.contextGen("bfv", n=2 ** 13, t=65537, sec=128) 
HE.keyGen() 
HE.rotateKeyGen() 
HE.relinKeyGen() 
arr3 = np.array([1, 2, 3])
ptxt3 = HE.encodeInt(arr3) 
ctxt3 = HE.encryptPtxt(ptxt3) 
cshift = ctxt3 << 2 
ccshift_dec = HE.decryptInt(ccshift)
print("last: ", ccshift_dec[8190])
print("first: ", ccshift_dec[0])

The output is:
last: 0
first: 3

**Comment by AlexanderViand** [comment]
Ohh, I see what's happening here, sorry for being a bit slow: There's a bit more complexity to how SEAL actually does rotations, and I guess Pyfhel doesn't really expose that to the user, nor does it take steps to abstract it away:

Your `a` and `b`are going to be at positions 4094 and 4095. This is because the actual rotation structure of SEAL isn't an N-element vector, it's a n/2 x 2 matrix. When using SEAL directly, there are both `rotate_vector` and `rotate_column`, and in the "summing-all-ctxts" algorithm, you first use `rotate_vector` to sum up each n/2 vector, and then you'd use `rotate_column` to align those two sums and get the final result. 

@ibarrond  We should consider either (a) reporting the batching size as n/2 to avoid this, or (b) making this more explicit and exposing rotate_column somehow, alternatively we could also think about (c) trying to somehow hide this by doing more work behind the scenes?

**Comment by meirgold** [comment]
Thanks for the explanation. Indeed when I print the 4095 and 4094 positions I see the numbers I expect.
But now I'm confused regarding the SEAL API exposed to python. Does the python implementation have both rotate_vector and rotate_column?
If it has only rotate_vector, is there any way to rotate the 2nd vector? 
also, what happens when I sum 2 contexts with the size of 2**13? will the sum consider this as one long vector?

**Comment by AlexanderViand** [comment]
It seems like Pyfhel only exposes `rotate_vector` at the moment (but @ibarrond might correct me here). If so, that's obviously a bug and we'll try to add `rotate_column` support soon-ish (However, development time for Pyfhel is currently very scarce).

I don't think there's a way to do the `rotate_column` at the moment. But you can probably work around that by simply selecting a larger n and only using the first half. Alternatively, not all applications require rotations over that second axis.

When you add two ciphertexts, it's element-wise additions. Basically, the same as if ciphertexts were an `n x n/2` matrix.

**Comment by meirgold** [comment]
Thanks for the explanations. I will do as you suggested and only use half of the n.

**Comment by AlexanderViand** [comment]
Sorry for the inconvenience!

**Comment by ibarrond** [comment]
As per version 3.3.0, you can call `HE.flip` on BFV ciphertexts to perform the `rotate_columns` operation from SEAL.

Additionally, a function named `HE.cumul_add` performs these rotations and cumulative additions automatically for you by simply giving a vector length `l` (where `l` must be a power of 2 for convenience). If `l>n/2` it will also perform `HE.flip` and sum the entire encrypted vector, thus you can safely use all the slots (`HE.get_nSlots()`).
