### ISSUE TITLE
Adding noise budget after many multiplications

### ISSUE THREAD

**Issue by meirgold** [ibarrond/Pyfhel#144]
In the "MultDepth and Relineraization" tutorial it is mentioned that once the noise budget reaches zero, the ciphertext cannot be decrypted correctly anymore. 
As I need to perform many multiplication operations,  I was wondering how I can add noise budget to my ciphertext. I tried increasing the "n" value from 2 ** 13 to 2**14. This resolved my problem for now, but I assume that when running with a larger amount of data and more multiplications,  I will reach the same issue again. 
I also tried decrypting and encrypting the ciphertext, but this didn't always work for me either. I wasn't fully able to understand the cases in which it worked vs. the cases in which it didn't. In addition, this would be the least preferred method for me to use.

I noticed that palisade support a "bootstrapping" or "recrypt" feature which can increase or reset the noise budget, but this isn't available in SEAL. 

Is there a different recommendation for performing many multiplicaton operations on a ciphertext and being able to decrypt it later?

**Comment by AlexanderViand** [comment]
Bootstrapping is very, very, very slow in practice, so it's unlikely that it would actually help you. You'll have to re-design your workload to have lower multiplicative depth. The idea of "client-aided refreshing" (sending the Ciphertext to the client, having them decrypt and encrypt freshly) is one way to do that. But if decryption sometimes fails for you, this means you're already doing too much computation for the given parameter set.  SEAL supports sizes of up to n=2**15 or 2**16, so you can try those, but operations will be noticeably slower at those sizes.

Note that there are two possibilities: 1.) The task you're trying to achieve is just too complex for current FHE (at least without hardware accelerators) or 2.) your task is achievable, but your algorithm isn't properly optimized for FHE. 
Without knowing what you're trying to do, it's hard to know which is the case.

**Comment by ibarrond** [comment]
Related to #88 and #112. The noise budget is of a fresh ciphertext is approximately `bitsize(q) - 2*bitsize(t)` for BFV, and directly related to the bitsize of `q` in CKKS. Hence, your best shot is to increase `q` to have space for more multiplication growth. Using `HE.contextGen(...)`:
- In BFV you can either select a higher `n` for a set value of `sec` (128 bits is more than enough!), provide your own `qi_sizes` or even provide your own choice of primes `qi`.
- In CKKS you can add more bitsizes to the `qi_sizes` list or provide your own list of primes `qi`.

There are however some side-effects arising from an increase of `q`:
- The more modulus in the `qi` chain, the more costly the operations become, since each polynomial coefficient is represented by as many numbers as there are elements in the modulus chain `qi` (the RNS representation).
- There is an upper limit to the bitsize of `q` that ties it to the poly_modulus_degree `n` to preserve the sevurity level `sec` (see table below). Besides, higher `n` fits more elements in a single ciphertext, making it larger and slower to operate with.
```
        +----------------------------------------------------+
        | poly_modulus_degree | max coeff_modulus bit-length |
        +---------------------+------------------------------+
        | 1024                | 27                           |
        | 2048                | 54                           |
        | 4096                | 109                          |
        | 8192                | 218                          |
        | 16384               | 438                          |
        | 32768               | 881                          |
        +---------------------+------------------------------+
```
I
