### ISSUE TITLE
contextGen() error

### ISSUE THREAD

**Issue by austinkipler** [ibarrond/Pyfhel#156]
//

**Comment by ibarrond** [comment]
In `Pyfhel>=3` the function `contextGen` takes a different number and type of parameters. You can check [Demos 1 to 3](https://github.com/ibarrond/Pyfhel/tree/master/examples) to find examples of usage for the BFV (integers) and CKKS (floating-point like) schemes. Otherwise you can always count on the up-to-date [documentation of contextGen()](https://pyfhel.readthedocs.io/en/latest/_autosummary/Pyfhel.Pyfhel.html#Pyfhel.Pyfhel.contextGen).

In your case, you seem to be missing the `scheme` (can be `bfv` or `ckks`) and the coefficient modulus `n` (number of elements).

**Comment by phuctran89** [comment]
When I change the HE setup as:
```
HE = Pyfhel(context_params={‘scheme’: ‘CKKS’, ‘n’: 2**14, ‘scale’:2**30, ‘qi_sizes’: [60, 30, 30, 30, 60]}, key_gen=True)
HE.rotateKeyGen()
```
How to implement these codes: 
```
pk_file = “client-pubkey.pk”
ctx_file = “client-context.ctx”
HE.savepublicKey(pk_file)
HE.saveContext(ctx_file)
```
as error:
```
AttributeError: ‘Pyfhel.Pyfhel.Pyfhel’ object has no attribute ‘savepublicKey’
