### ISSUE TITLE
How to manage Keys separately

### ISSUE THREAD

**Issue by sekar93** [ibarrond/Pyfhel#20]
Hello,

is it possible to manage the keys separately?

**Comment by ibarrond** [comment]
Yes it is! First you need to generate a key pair using `keyGen()`. Both a private and a public key will be generated. If you want to save them in a file, use the functions `savepublicKey(str filename)` and `savesecretKey(str filename)`. In order to recover them in a different context, just use `restorepublicKey(str filename)` and `restoresecretKey(str filename)` respectively. 

FYI, the relinearization keys (required when performing a lot of multiplications without decrypting) and the rotation keys (only applicable in batch mode, to rotate values inside a ciphertext) can also be treated the same way using their respective `save` and `restore` functions.

Thanks to your question, I will be producing a Demo about key management wiht Pyfhel.
