### ISSUE TITLE
How to print the ciphertext for BFV/CKKS scheme?

### ISSUE THREAD

**Issue by cyber-titan** [ibarrond/Pyfhel#227]
I am currently trying to learn Homomorphic Encryption using Pyfhel but I ran into some problem.

I want to know how to print the ciphertext and keys used for encryption and decryption for the BFV and CKKS schemes so that I can print the encrypted result. I was thinking of making a GUI to show that encrypted result and keys can be copied by the user and be used for decryption in the GUI.

**Comment by ShokofehVS** [comment]
You'll indeed enjoy learning HE with Pyfhel as I did due to its easy to test examples. 

Did you try reading tutorials for [BFV](https://pyfhel.readthedocs.io/en/latest/_autoexamples/Demo_2_Integer_BFV.html), and [CKKS](https://pyfhel.readthedocs.io/en/latest/_autoexamples/Demo_3_Float_CKKS.html)? There are very clear examples on how to print plaintext, ciphertext and do some computations.

**Comment by ibarrond** [comment]
If you want the actual encrypted bytes for some reason, just serialize without compression and print the serialized objects.
However! note that the keys and ciphertexts are often very large, and thus they might overflow the clipboard when attempting to copy-paste! It might be easier to just save them in files and load them from files (as suggested by @ShokofehVS, there are examples to achieve this in the `examples` folder).

**Comment by ibarrond** [comment]
Closing, the comments above answer the question.

**Comment by cyber-titan** [comment]
Yeah thanks for the help guys
