### ISSUE TITLE
scale mismatch

### ISSUE THREAD

**Issue by scutyuqiu** [ibarrond/Pyfhel#235]
File "Pyfhel/PyCtxt.pyx", line 360, in Pyfhel.PyCtxt.PyCtxt.__add__ 
File "Pyfhel/Pyfhel.pyx", line 1050, in Pyfhel.Pyfhel.Pyfhel.add_plain 
File "Pyfhel/Pyfhel.pyx", line 1070, in Pyfhel.Pyfhel.Pyfhel.add_plain
 ValueError: scale mismatch

How can I resolve this error?

I use homomorphic encryption in neural networks. At the full connection layer, the encrypted data has been weighted, but this error occurs when adding with bias.

[code.docx](https://github.com/ibarrond/Pyfhel/files/14918713/code.docx)

**Comment by ShokofehVS** [comment]
Hi @scutyuqiu, I reviewed issues on Pyfhel and demos, I found [one](https://github.com/ibarrond/Pyfhel/blob/51840a76999a538c764f0abab25bb18f605361f7/examples/Demo_WAHC21.py#L140) that is helpful for you to read (exploring CKKS pitfalls). 

I can recall that I faced similar issue and fixed that with rescaling ([HE.rescale](https://pyfhel.readthedocs.io/en/latest/_autoexamples/Demo_3_Float_CKKS.html#rescaling-mod-switching)) as also pointed out in this [issue](https://github.com/microsoft/SEAL/issues/64#issuecomment-541228430) on SEAL because when you are doing multiplication, you'll have ciphertext in different scale (compared to addition/subtraction) then addition wont work properly as you desired.

**Comment by scutyuqiu** [comment]
I solved the problem, but I was curious. It doesn't work when I set qi to 21, but it works when I set it to 22.

**Comment by ShokofehVS** [comment]
Well-done!

`qi_size` is about the number of bits of each prime in the chain to ensure precision in encoding and decoding. However, I also dont have any connection now in mind between your scale mismatch and `qi_size`.
