### ISSUE TITLE
Cannot do addition when I put the loaded ciphertext first

### ISSUE THREAD

**Issue by 767472021** [ibarrond/Pyfhel#32]
Oh,I met a new problem when I try to do addition between two loaded ciphertext.After serveral try,I found if we put the loaded ciphertext first when doing computation it will throw a bug
`AttributeError: 'NoneType' object has no attribute 'add'`.In fact,the ciphertext could be loaded and decrypted correctly.So we are now in trouble and need your help.

**Comment by marcwil** [comment]
Could you paste a minimal example code snippet? I'm not sure what you mean by putting ciphertext first / loaded ciphertext.

**Comment by 767472021** [comment]
Code_demo:

```
ctxt1 = HE.encryptInt(integer1)
ctxt1.save("ctxt")
loaded = PyCtxt()
loaded.load("ctxt")
sum1 = loaded + loaded
print(HE.decryptInt(sum1))
```

Bug:
`AttributeError: 'NoneType' object has no attribute 'add'`

**Comment by marcwil** [comment]
Yeah I see.

The `__add__` function that is used when applying the `+` operator uses an internal reference to the Pyfhel object it is associated with, `_pyfhel`.

By saving a ciphertext to a file, the Pyfhel reference is lost. This is okay, because after restoring the ciphertext from the file, the Pyfhel object might have been restored from a file as well and the old reference won't be correct anymore.

We have two ways of solving this problem:
1. Using Pyfhel.add instead of Ciphertext's + operator
```
ctxt1 = HE.encryptInt(integer1)
ctxt1.save("ctxt")
loaded = PyCtxt()
loaded.load("ctxt")
sum1 = HE.add(loaded, loaded)
print(HE.decryptInt(sum1))
```
2. Manually assigning the `_pyfhel` reference
```
ctxt1 = HE.encryptInt(integer1)
ctxt1.save("ctxt")
loaded = PyCtxt()
loaded.load("ctxt")
loaded._pyfhel = HE
sum1 = loaded + loaded
print(HE.decryptInt(sum1))
```

I hope this helps and I agree that this is not made as clear as it should be by the documentation.

**Comment by 767472021** [comment]
Thank you very much for helping me solve the big problem.
