### ISSUE TITLE
Installation Error "SEAL requires GNUC >= 6"

### ISSUE THREAD

**Issue by maheshidrbt** [ibarrond/Pyfhel#35]
I downloaded Pyfhel and when i am trying to install errors was occurred. I am attaching the screen shots of errors. Please help me to properly install Pyfhel and use the library.
![error1](https://user-images.githubusercontent.com/49904269/56572912-9ac09180-65dd-11e9-8f2e-b5b0810da0d7.png)
![error2](https://user-images.githubusercontent.com/49904269/56572913-9ac09180-65dd-11e9-93b6-3b746f8453ee.png)

**Comment by ibarrond** [comment]
This means that your Python3 is not built with a compiler that supports C++14. Tipically, as it is your case, Ubuntu 16.04 uses `gcc` version 5.4 as default compiler, and its Python3 is built with it. To solve it you heed to obtain a Python3 version built with a commpiler supporting C++14, in the case of `gcc` it is version 6. There are two options to solve it in Ubuntu 16.04:
1. Install gcc 6+ and then build and install Python3 from source.
2. Upgrade to Ubuntu 18.04, since the default compiler is `gcc` v7.2.
