### ISSUE TITLE
How to extract the symbol bits of encrypted data separately？

### ISSUE THREAD

**Issue by zhhhhhh** [ibarrond/Pyfhel#56]
Dear developer, I want to extract the symbol bits of encrypted data separately, and then decrypt the encrypted symbol bits. What should I do?

**Comment by ibarrond** [comment]
I'm afraid I don't follow. Could you provide an example?

**Comment by zhhhhhh** [comment]
Suppose a negative number -1 is encrypted, and its ciphertext ENC(11) is obtained after encoding and encrypting. I want to extract the encrypted symbol bit of ENC(11), that is, ENC(1), to carry out other operation, such as ENC(1) * OtherCtext. How can I extract the encrypted symbol bit of ENC(11)?

**Comment by ibarrond** [comment]
I'm afraid that is not possible.

Pyfhel doesn't offer that functionality, SEAL doesn't offer it either, and I'm quite sure this is indeed because FHE does not support **bit extraction** at all. Otherwise you could extract the sign of a ciphertext using this operation, allowing you to compute extremely cheap non-linear functions. FHE doesn't support non-linear functions.

**Comment by zhhhhhh** [comment]
I am not very clear about the encryption part of homomorphism. What I understand is that they are encrypted by bit. For example, a plaintext is encoded in binary form, the highest bit is its sign bit, and then the plaintext encrypts by bit and get the ciphertext with n-length: c1, c2, ..., cn; Then c1 is the encrypted ciphertext of the sign bit.

That's what I understand, so I want to extract c1 and do something else.

May I ask if there is anything wrong with my idea？Thank you.

**Comment by zhhhhhh** [comment]
What I ultimately want to achieve is really a nonlinear function **RELU**, and I want to reconstruct this function by extracting the encrypted sign bit and other operations, rather than by decrypting the data.

Can you give me some suggestions? Thank you very much.

**Comment by ibarrond** [comment]
The **encoding** looks more or less like that, depending on the base of the polynomials (the `base` parameter in Pyfhel context). If you want one bit per polynomial, then use `base=2` (you can play with this in Pyfhel by using multiple bases to encode different values into `PyPtxt` and then printing their endoded polynomials using `.to_string()`).

However, the **encryption** requires the entire set of polynomials (even those that are set to 0), and uses the public key to add noise to the entire set at once. In order to remove this noise and decrypt, you need the entire set of noisy polynomials. You cannot extract individual polynomials and decrypt them because the **decrypt** operation works at ciphertext level (the denoising only makes sense on the vectorial space defined by the grouped polynomials).

Your inquiry about **RELU** is a very common one, and treated extensively in literature (just type "non linear activation homomorphic encryption" in Google Scholar). The two standard approaches are:
1. Use linear activation functions instead ([square](http://proceedings.mlr.press/v48/gilad-bachrach16.pdf), [polynomial approximations of RELU](https://arxiv.org/abs/1711.05189)).
2. Switch to Garbled Circuits for this computation (e.g.: [Gazelle](https://eprint.iacr.org/2018/073.pdf)).

**Comment by zhhhhhh** [comment]
I see. Thank you very much for your advice.
