### ISSUE TITLE
Documentation lacks argument in restore of data

### ISSUE THREAD

**Issue by AlbertoPimpo** [ibarrond/Pyfhel#67]
In some functions (at the moment I saw only from_bytes and from_file) in the documentation is reported that those functions has only one argument (the string or path of the data) but it needs also another parameter in order to understand how to parse it (if i can suggest an improvement i think it will be better if you have to insert directly the class int, float, or array instead of the string).
https://pyfhel.readthedocs.io/en/latest/#Pyfhel.PyCtxt.from_bytes (pointing to the documentation)

As last time congrats and thanks for the project.

**Comment by ibarrond** [comment]
It looks like the docs are a bit outdated! Indeed you can use the `int`, `float` and `list` classes instead of the equivalent `'int'`,  `'float'` and `'array'` strings. To be precise, every `encoding` argument you may find (notably those in `from_bytes` and `from_file`) is given as input to the function 'to_ENCODING_t()' for sanitation. 

https://github.com/ibarrond/Pyfhel/blob/3ce85c14f3644a8eac961092335befad3a8169a4/Pyfhel/util/utils.pxi#L15

This means that `encoding` can be one of:
- string: `'int'`|`'integer'` (or anything starting by `i`) for INTEGER encoding, `'float'`|`'double'` (or anything starting by `f` or `d`)  for FRACTIONAL encoding, `'array'`|`'batch'`|`'matrix'` (or anything starting by `a`, `b` or `m`)  for BATCH encoding.
- Python class: `int` for INTEGER encoding, `float` for FRACTIONAL encoding, `list` for BATCH encoding.
- Number: `1`|`1.0` for INTEGER encoding, `2`|`2.0`  for FRACTIONAL encoding, `3`|`3.0` for BATCH encoding.
- A valid ENCODING_t Enum (belonging to [this class](https://github.com/ibarrond/Pyfhel/blob/master/Pyfhel/util/ENCODING_t.py#L2)): `ENCODING_t.INTEGER` for INTEGER encoding, `ENCODING_t.FRACTIONAL`  for FRACTIONAL encoding, `ENCODING_t.BATCH` for BATCH encoding.

**Comment by AlbertoPimpo** [comment]
Ok, thanks for the explanation.

**Comment by ibarrond** [comment]
As of v2.2.5, the documentation has been greatly updated! This is the new explanation:

https://pyfhel.readthedocs.io/en/latest/_autosummary/Pyfhel.PyCtxt.html#Pyfhel.PyCtxt.from_file

More in detail: https://pyfhel.readthedocs.io/en/latest/_autosummary/Pyfhel.util.to_ENCODING_t.html
