### ISSUE TITLE
Docker install

### ISSUE THREAD

**Issue by NilsHendrikLukas** [ibarrond/Pyfhel#7]
Include a dockerfile for easy setup

**Comment by tdonovic** [comment]
Used this dockerfile
`FROM ubuntu:bionic
RUN apt-get update && apt-get install lzip git make sudo -y
RUN git clone --recursive https://github.com/ibarrond/Pyfhel
RUN cd Pyfhel/src && ./configure && make all`

And installation fails at 
`----------------------------AFHEL MAKEFILE-----------------------------
Afhel requires HElib, NTL version 10.0.0 or higher and GMP
For a list if all the available commands, run >make info
libtool --mode=compile g++ -g -O2 -std=c++11 -I/usr/local/include -pthread -DFHE_THREADS -DFHE_DCRT_THREADS -DFHE_BOOT_THREADS -Wfatal-errors -Wshadow -Wall -fmax-errors=2 -fpic -c Afhel.cpp
libtool: compile:  g++ -g -O2 -std=c++11 -I/usr/local/include -pthread -DFHE_THREADS -DFHE_DCRT_THREADS -DFHE_BOOT_THREADS -Wfatal-errors -Wshadow -Wall -fmax-errors=2 -fpic -c Afhel.cpp  -fPIC -DPIC -o .libs/Afhel.o
In file included from Afhel.cpp:46:0:
Afhel.h:96:9: warning: "/*" within comment [-Wcomment]
         /**

Afhel.cpp:50:14: error: definition of implicitly-declared 'Afhel::Afhel()'
 Afhel::Afhel(){}
              ^
compilation terminated due to -Wfatal-errors.
Makefile:145: recipe for target 'Afhel.lo' failed
make[1]: Leaving directory '/Pyfhel/src/Afhel'
make[1]: *** [Afhel.lo] Error 1
Makefile:133: recipe for target 'Afhel' failed
make: *** [Afhel] Error 2
The command '/bin/sh -c cd Pyfhel/src && ./configure && make all' returned a non-zero code: 2`

Any ideas?

**Comment by tanu17** [comment]
@tdonovic Afhel.h should have a closing brace "*/" for the comments in line 76. The omission of "/" is giving the error

**Comment by ibarrond** [comment]
I'm almost finished with a complete rework of this library (you can sneak peek on branch version2). Hopefully this issue will be solved.

**Comment by tanu17** [comment]
@ibarrond thank you for the timely reply. The sudo make install is running correctly. But running any python demo file gives an error "ImportError: No module named Pyfhel" which may due to the absence of Pfhel/setup.py in version2 branch

**Comment by ibarrond** [comment]
Uf, as of today all the demos are outdated, as well as the installation process. I'm fighting to upload the whole package to PyPI so that installation is considerably easier. Stay tuned!

**Comment by ibarrond** [comment]
Installing in docker should be straightforward now by running `pip install Pyfhel`. To make sure that C++17 support is included, just run the commands present in [travis.yml](https://github.com/ibarrond/Pyfhel/blob/master/.travis.yml):

```bash
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-6 g++-6 -y
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
pip install Pyfhel
```
