### ISSUE TITLE
How to pickle an encrypted(fractional) Numpy array?

### ISSUE THREAD

**Issue by busranurbulbul** [ibarrond/Pyfhel#81]
I am trying to send encrypted array by using socket. I tried pickle.dump() for sending data but there is an error;
```
    data_string = pickle.dumps(X)
  File "stringsource", line 2, in Pyfhel.PyCtxt.PyCtxt.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```

I tried to run your clientServerDemo, but it did not run for NumpyArray.

Do you have any advice?

**Comment by ibarrond** [comment]
Instead of using pickle (which is not supported), convert ciphertexts to bytes using the `to_bytes` method and concatenate. Then send the result as a payload. Alternatively, save the ciphertexts files and send those files. 

Nonetheless, this functionality seems very useful! I'll add it to the list. If you have the time, I could indicate you where to touch in order to implement it.

**Comment by ibarrond** [comment]
Heads up, pickling will be supported soon! I tested it today and it seems to be working nicely with the Numpy demo. Stay tuned!

**Comment by ibarrond** [comment]
@busranurbulbul Pickling is now supported! Have a look at the SaveNRestore demo for basic usage, and the Numpy demo for usage with arrays of fractionals. If you see anything hard to understand, do not hesitate to modify it in a pull request.

**Comment by busranurbulbul** [comment]
@ibarrond Thank you for your contributions.
